name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CHANGESETS_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
          title: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
